#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor DP-0 -d I II III IV V

# USE THIS FOR 144Hz
bspc config pointer_motion_interval 7ms

bspc config border_width         3
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config active_border_color '#002b36'
bspc config normal_border_color '#002b36'
bspc config focused_border_color '#073642'
bspc config presel_feedback_color "#b58900"
# bspc config -m HDMI-0 top_padding 0
bspc config -m DP-0 top_padding 35
bspc config -m DP-0 bottom_padding 0
bspc monitor DP-0 -d 4 5 6
bspc monitor HDMI-0 -d 1 2 3

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
