#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor DP-0 -d I II III IV V

# USE THIS FOR 144Hz
bspc config pointer_motion_interval 7ms

bspc config border_width         5
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color '#242424'
bspc config normal_border_color '#242424'
bspc config focused_border_color '#424242'
bspc config presel_feedback_color "#db8712"
# bspc config -m HDMI-0 top_padding 0
bspc config -m DP-0 top_padding 35
bspc config -m DP-0 bottom_padding 0
bspc monitor DP-0 -d 1 2 3
bspc monitor HDMI-0 -d 4 5 6

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
